"""hs-mod CLI — Half-Sword Mod Factory

Core commands for the autonomous pipeline:
  new <slug> [--type ...] [--desc "..."]     Create a new pack
  list                                       List packs in ./packs
  workon <slug>                              Print cd command + basic info
  generate-lua <slug>                        Generate excellent UE4SS Lua (slow-mo, buff, etc.)
  build <slug>                               Build the pack with repak (now visual aware)
  publish <slug> ...                         Publish to GitHub
  prep-visual <slug> [--category kitchen|props|weapons] [--execute]
                                             Read RAW_HOME, drive unpack-selective.sh + catalog suggestions,
                                             prepare assets-src/ for visual mods, declare visual in manifest.
                                             Packer auto-includes from Content/ or assets-src/cooked/.

Run with --help on any command for details.
"""

import argparse
import json
import os
import subprocess
import sys
from pathlib import Path

from .manifest import ModManifest, create_default_manifest, DEFAULT_MANIFEST
from .generators.lua_generator import generate_ue4ss_mod
from .packer import build_pack
from .publish import publish_with_gh

# Repo root is two levels up from src/hsmod/cli.py when run as module
REPO_ROOT = Path(__file__).resolve().parents[2]
PACKS_DIR = REPO_ROOT / "packs"


def get_raw_home() -> Path | None:
    """Read RAW_HOME file (or HS_RAW_HOME env) so the autonomous factory can see and use the raw pak home for asset work."""
    env = os.environ.get("HS_RAW_HOME")
    if env:
        p = Path(env).expanduser()
        if p.exists():
            return p
    raw_file = REPO_ROOT / "RAW_HOME"
    if raw_file.exists():
        for line in raw_file.read_text(encoding="utf-8").splitlines():
            line = line.strip()
            if line and not line.startswith("#"):
                p = Path(line).expanduser()
                return p
    return None


def get_kitchen_filters(category: str | None = None) -> list[str]:
    """Small helper that knows common kitchen filters and can launch the unpack-selective.sh from RAW_HOME."""
    base = "HalfswordUE5/Content/Assets/"
    if category == "props":
        return [
            f"{base}Props/Barrels/Meshes",
            f"{base}Props/Cooking_Utencils",
        ]
    if category == "weapons":
        return [
            f"{base}Weapons/Axes/Meshes",
            f"{base}Weapons/Swords/Meshes",
        ]
    # default: kitchen (or all)
    return [
        f"{base}Props/Barrels/Meshes",
        f"{base}Props/Cooking_Utencils",
        f"{base}Weapons/Axes/Meshes",
    ]


def cmd_new(args: argparse.Namespace) -> int:
    slug = args.slug.strip().lower().replace(" ", "-")
    if not slug or not slug.replace("-", "").isalnum():
        print(f"[error] Invalid slug: {slug}")
        return 1

    pack_dir = PACKS_DIR / slug
    if pack_dir.exists():
        print(f"[error] Pack already exists: {pack_dir}")
        return 1

    pack_dir.mkdir(parents=True, exist_ok=False)

    # Manifest
    manifest = create_default_manifest(slug, name=args.name)
    manifest.type = args.type
    manifest.description = args.desc or f"Autonomously generated {args.type} pack for Half-Sword."
    manifest.save(pack_dir / "manifest.json")

    # Basic README
    readme = f"""# {manifest.name}

**Slug**: `{slug}`  
**Version**: {manifest.version}  
**Type**: {manifest.type}  
**Generated by**: Grok Half-Sword Mod Factory

{manifest.description}

## Install

1. Install UE4SS (see research docs).
2. Copy files from `build/` and `ue4ss-mods/` as instructed by the pipeline.
3. Launch and enjoy.

## Commands (in this pack)

- `GrokTest` — placeholder (will be replaced by generator)

See the parent repo README and docs/ for the full autonomous pipeline.
"""
    (pack_dir / "README.md").write_text(readme, encoding="utf-8")

    # Standard subdirs
    (pack_dir / "ue4ss-mods" / slug.replace("-", "_").title() / "Scripts").mkdir(parents=True)
    (pack_dir / "Content").mkdir()
    (pack_dir / "assets-src").mkdir()
    (pack_dir / "build").mkdir()

    # Placeholder Lua
    lua_path = pack_dir / "ue4ss-mods" / slug.replace("-", "_").title() / "Scripts" / "main.lua"
    lua_path.write_text(f"""-- {manifest.name} — UE4SS Lua mod
-- Generated by hs-mod new
print("[{slug}] Mod loaded. Replace this with real logic from the generator.")

RegisterConsoleCommand("GrokTest", function()
    print("GrokTest command from {slug} works!")
end)
""", encoding="utf-8")

    print(f"[ok] Created pack at: {pack_dir}")
    print("Next steps:")
    print(f"  cd {pack_dir}")
    print("  # edit ue4ss-mods/.../main.lua and/or drop textures")
    print(f"  {REPO_ROOT}/scripts/hs-mod build {slug}")
    return 0


def cmd_list(_: argparse.Namespace) -> int:
    if not PACKS_DIR.exists():
        print("No packs directory yet.")
        return 0

    packs = [p for p in PACKS_DIR.iterdir() if p.is_dir() and (p / "manifest.json").exists()]
    if not packs:
        print("No packs found in ./packs")
        return 0

    print("Available packs:")
    for p in sorted(packs):
        try:
            m = ModManifest.load(p / "manifest.json")
            print(f"  {p.name:30}  v{m.version}  [{m.type}]  — {m.name}")
        except Exception as e:
            print(f"  {p.name:30}  (invalid manifest: {e})")
    return 0


def cmd_workon(args: argparse.Namespace) -> int:
    slug = args.slug
    pack_dir = PACKS_DIR / slug
    if not pack_dir.exists():
        print(f"[error] Pack not found: {pack_dir}")
        return 1

    print(f"cd {pack_dir}")
    print(f"# Now inside {slug}. Use ls, edit files, then run build.")
    try:
        m = ModManifest.load(pack_dir / "manifest.json")
        print(f"# Current: {m.name} v{m.version} ({m.type})")
    except Exception:
        pass
    return 0


def cmd_build(args: argparse.Namespace) -> int:
    slug = args.slug
    try:
        result = build_pack(slug)
        print(f"[build] Pack '{slug}' processed successfully.")
        for out in result.get("outputs", []):
            print(f"  -> {out}")
        if "repak_error" in result:
            print(f"[warning] repak issue: {result['repak_error']}")
        if "manual_instruction" in result:
            print(f"[info] {result['manual_instruction']}")
        return 0
    except Exception as e:
        print(f"[error] Build failed: {e}")
        return 1


def cmd_publish(args: argparse.Namespace) -> int:
    slug = args.slug
    gh_user = getattr(args, "gh_user", None) or "YOUR_GH_USERNAME"
    result = publish_with_gh(slug, gh_user)
    print(f"[publish] {result['status'].upper()}")
    print(result.get("instructions", result.get("note", "")))
    print("\nFor full MCP autonomy: follow the search_tool + use_tool steps in docs/publishing.md")
    return 0


def cmd_generate_lua(args: argparse.Namespace) -> int:
    """Generate a high-quality UE4SS Lua file for a pack."""
    slug = args.slug
    pack_dir = PACKS_DIR / slug
    if not pack_dir.exists():
        print(f"[error] Pack not found: {pack_dir}")
        return 1

    mod_name = slug.replace("-", " ").title().replace(" ", "")
    code = generate_ue4ss_mod(
        mod_name=mod_name,
        commands=None,  # uses excellent defaults (slow, fast, normal, buff)
        include_health_buff=True,
    )

    # Write into the ue4ss-mods folder created by `new`
    target_dir = pack_dir / "ue4ss-mods" / mod_name / "Scripts"
    target_dir.mkdir(parents=True, exist_ok=True)
    target = target_dir / "main.lua"
    target.write_text(code, encoding="utf-8")

    print(f"[ok] Generated rich UE4SS Lua at: {target}")
    print("Commands included: GrokSlow, GrokFast, GrokNormal, GrokBuff")
    return 0


def cmd_prep_visual(args: argparse.Namespace) -> int:
    """Prepare visual/asset work using RAW_HOME + selective unpack.

    This is the new command for autonomous visual mod creation (kitchen weapons, props, etc.).
    """
    slug = args.slug or getattr(args, "target", None)
    category = args.category
    custom_filters = args.filters or []
    execute = args.execute

    print("[prep-visual] Making factory see RAW_HOME for asset discovery and prep...")

    raw_home = get_raw_home()
    if not raw_home:
        print("[error] No RAW_HOME found. Create RAW_HOME file or set HS_RAW_HOME env var.")
        return 1
    print(f"[ok] RAW_HOME resolved to: {raw_home}")

    unpack_script = raw_home / "scripts" / "unpack-selective.sh"

    if custom_filters:
        filters = custom_filters
    else:
        filters = get_kitchen_filters(category)

    print(f"[info] Category '{category or 'kitchen'}' -> filters: {filters}")

    print("[info] Equivalent manual command:")
    print(f"  cd {raw_home}")
    print(f"  bash {unpack_script} {' '.join(repr(f) for f in filters)}")

    if execute and unpack_script.exists():
        print("[exec] Running unpack...")
        try:
            subprocess.run([str(unpack_script)] + filters, cwd=str(raw_home), check=False)
        except Exception as e:
            print(f"[warn] Unpack script error: {e}")
    else:
        print("[info] (dry by default) Re-run with --execute to actually invoke the unpack script.")

    # Ensure pack structure
    if slug:
        pack_dir = PACKS_DIR / slug
        if pack_dir.exists():
            for sub in ["assets-src/OriginalRefs", "assets-src/Textures", "Content", "assets-src/KitchenWeapons", "assets-src/KitchenProps"]:
                (pack_dir / sub).mkdir(parents=True, exist_ok=True)
            print(f"[ok] Ensured asset directories under {pack_dir}")

            # Update manifest
            try:
                m = ModManifest.load(pack_dir / "manifest.json")
                m.visual = True
                if not hasattr(m, "asset_targets") or not m.asset_targets:
                    m.asset_targets = ["kitchen props", "weapons"]
                m.save(pack_dir / "manifest.json")
                print("[ok] Manifest updated with visual: true and asset_targets")
            except Exception:
                pass

    # Show catalog suggestions if present
    catalog = raw_home / "ASSET_CATALOG.md"
    if catalog.exists():
        print("\n--- Catalog suggestions (from ASSET_CATALOG.md) ---")
        text = catalog.read_text(encoding="utf-8")
        for line in text.splitlines():
            if "Next unpacks recommended" in line or "Barrels" in line or "Cooking" in line:
                print(line)
                break
        print("--- end suggestions ---")
        print(f"Full catalog: {catalog}")

    print(f"\n[guide] Raw workspace README + setup: {raw_home / 'README-workspace.md'}")
    print(f"[guide] Detailed asset workflows + UE cook: {REPO_ROOT / 'docs/asset-workflows.md'}")
    print("[guide] Packer now supports visual overrides from pack/Content/ or pack/assets-src/cooked/ (with HalfswordUE5/ tree)")

    print("""
Typical flow now supported:
  hs-mod prep-visual kitchen-mayhem --category kitchen --execute
  # (after manual cook in UE) copy cooked to pack/Content/ or assets-src/cooked/
  hs-mod build <slug>
  # packer will detect and include in .pak with correct mount point
""")
    return 0


def main(argv: list[str] | None = None) -> int:
    if argv is None:
        argv = sys.argv[1:]

    parser = argparse.ArgumentParser(
        prog="hs-mod",
        description="Half-Sword Mod Factory CLI — autonomous pipeline for creating and publishing UE 5.4.4 mod packs."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    # new
    p_new = sub.add_parser("new", help="Create a new mod pack")
    p_new.add_argument("slug", help="Short unique name, e.g. dark-fantasy-flail")
    p_new.add_argument("--name", help="Human readable name")
    p_new.add_argument("--type", default="ue4ss,texture-swap", help="Comma-separated types (ue4ss,texture-swap,full-asset...)")
    p_new.add_argument("--desc", help="Short description")
    p_new.set_defaults(func=cmd_new)

    # list
    p_list = sub.add_parser("list", help="List existing packs")
    p_list.set_defaults(func=cmd_list)

    # workon
    p_work = sub.add_parser("workon", help="Switch context to a pack (prints cd command)")
    p_work.add_argument("slug")
    p_work.set_defaults(func=cmd_workon)

    # build (stub)
    p_build = sub.add_parser("build", help="Build/package the mod (repak)")
    p_build.add_argument("slug")
    p_build.set_defaults(func=cmd_build)

    # publish
    p_pub = sub.add_parser("publish", help="Publish pack to GitHub (gh or MCP)")
    p_pub.add_argument("slug")
    p_pub.add_argument("--gh-user", default="YOUR_GH_USERNAME", help="GitHub username for repo creation")
    p_pub.set_defaults(func=cmd_publish)

    # generate-lua
    p_lua = sub.add_parser("generate-lua", help="Generate high-quality UE4SS Lua (TimeDilation + health)")
    p_lua.add_argument("slug", help="Pack slug to generate Lua for")
    p_lua.set_defaults(func=cmd_generate_lua)

    # NEW: prep-visual
    p_vis = sub.add_parser("prep-visual", help="Prep visual assets from raw paks (kitchen weapons/props etc). Enables autonomous asset-swap flows.")
    p_vis.add_argument("slug", nargs="?", help="Pack slug e.g. kitchen-mayhem (updates its manifest for visual)")
    p_vis.add_argument("--target", help="Pack slug target (alternative to positional)")
    p_vis.add_argument("--category", choices=["kitchen", "props", "weapons"], help="Use predefined kitchen filters from helper + catalog")
    p_vis.add_argument("--filters", nargs="*", help="Custom filter paths for unpack-selective.sh")
    p_vis.add_argument("--execute", action="store_true", help="Actually run the unpack script (default: dry-run, print command only)")
    p_vis.set_defaults(func=cmd_prep_visual)

    if not argv:
        parser.print_help()
        return 0

    args = parser.parse_args(argv)
    return args.func(args)


if __name__ == "__main__":
    raise SystemExit(main())
